### PR TITLE
Add user 1000 in base image

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Review by srbala — APPROVED** [review]
LGTM

**Comment by srbala** [comment]
Its good to see image run using NON root user

**Comment by StrongMonkey** [comment]
https://github.com/rancher/fleet/issues/216

**Comment by boxboatmatt** [comment]
This will also need to be added to `rancher/gitjob` image

**Comment by boxboatmatt** [comment]
https://github.com/rancher/gitjob/pull/26

**Review by dramich — APPROVED** [review]

**Pull request merged**
